Layout/AccessModifierIndentation:
  Exclude:
    - 'app/controllers/loans_controller.rb'

Layout/DefEndAlignment:
  Exclude:
    - 'app/controllers/signup_controller.rb'
    - 'app/controllers/users_controller.rb'

Layout/EmptyLineAfterGuardClause:
  Exclude:
    - 'bin/bundle'

Layout/EmptyLineBetweenDefs:
  Exclude:
    - 'app/controllers/loans_controller.rb'
    - 'app/controllers/signup_controller.rb'
    - 'app/controllers/users_controller.rb'

Layout/EmptyLines:
  Exclude:
    - 'Gemfile'
    - 'app/controllers/loans_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'config/initializers/assets.rb'
    - 'config/routes.rb'
    - 'spec/**/*'  # Exclude the spec folder

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'config/routes.rb'

Layout/EmptyLinesAroundClassBody:
  Exclude:
    - 'app/controllers/loans_controller.rb'
    - 'app/controllers/pages_controller.rb'
    - 'app/controllers/signup_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/models/loan.rb'

Layout/EmptyLinesAroundMethodBody:
  Exclude:
    - 'db/migrate/20240111133345_add_new_columns_toloans.rb'
    - 'db/migrate/20240121155815_add_fields_to_loan.rb'
    - 'db/migrate/20240121163339_addempdetailtoloans.rb'
    - 'db/migrate/20240122084639_change_data_type_inloans.rb'

Layout/IndentationWidth:
  Exclude:
    - 'app/controllers/custom_sessions_controller.rb'
    - 'app/controllers/loans_controller.rb'
    - 'app/controllers/pages_controller.rb'
    - 'app/controllers/signup_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/models/loan.rb'
    - 'db/migrate/20240122052008_change_data_type_in_loans.rb'
    - 'db/migrate/20240122084639_change_data_type_inloans.rb'

Layout/LeadingCommentSpace:
  Exclude:
    - 'app/controllers/loans_controller.rb'

Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'config/environments/production.rb'

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/environments/production.rb'

Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    - 'Gemfile'

Layout/TrailingEmptyLines:
  Exclude:
    - 'app/controllers/custom_sessions_controller.rb'
    - 'app/controllers/signup_controller.rb'
    - 'db/migrate/20240118064355_add_user_role_to_users.rb'

Layout/TrailingWhitespace:
  Exclude:
    - 'app/controllers/loans_controller.rb'
    - 'app/controllers/signup_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'config/environments/development.rb'

Lint/UnusedMethodArgument:
  Exclude:
    - 'app/controllers/signup_controller.rb'

Lint/UselessAssignment:
  Exclude:
    - 'app/controllers/loans_controller.rb'

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 40
  Exclude:
    - 'app/controllers/loans_controller.rb'

Metrics/PerceivedComplexity:
  Max: 30

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/users/registrations_controller.rb'
    - 'app/controllers/users/confirmations_controller.rb'
    - 'app/controllers/users/omniauth_callbacks_controller.rb'
    - 'app/controllers/users/passwords_controller.rb'
    - 'app/controllers/users/sessions_controller.rb'
    - 'app/controllers/users/unlocks_controller.rb'

Style/ConditionalAssignment:
  Exclude:
    - 'app/controllers/loans_controller.rb'

Style/Documentation:
  Enabled: false
  Exclude:
    - 'app/controllers/loans_controller.rb'

Style/EmptyMethod:
  Exclude:
    - 'app/controllers/pages_controller.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'app/controllers/custom_sessions_controller.rb'
    - 'bin/bundle'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/PercentLiteralDelimiters:
  Exclude:
    - 'config/application.rb'

Style/PerlBackrefs:
  Exclude:
    - 'bin/bundle'

Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 10

Layout/LineLength:
  Max: 252
  Exclude:
    - 'spec/**/*'
